### ISSUE TITLE
404 - Not found 

### ISSUE THREAD

**Issue by kweitzner** [ChuckMac/ADRFinder#8]
Running via docker, container starts, on trying to navigate to the localhost 

Creating JSON store at /datastore
(1) wsgi starting up on http://0.0.0.0:5500
(1) accepted ('192.168.50.31', 62247)
>> Request failed: 404 Client Error: Not Found for url: https://disneyworld.disney.go.com/dining/

192.168.50.31 - - [29/Jul/2022 18:01:08] "GET / HTTP/1.1" 200 0 0.175413
wsgi exiting
(1) wsgi exited, is_accepting=True

Seems they've modified URL, I am unsure if they made any other breaking changes.

**Comment by f5snopro** [comment]
Same issue for me. Any updates on a fix? I haven't yet been able to use but looks awesome.

**Comment by f5snopro** [comment]
Really appreciate the quick response here -- I empathize with the lack of time.  I'll continue to keep on eye out. Have my son's 10th birthday coming up middle of next month and was just trying to score a decent reservation for him to celebrate.

**Comment by ChuckMac** [comment]
I spent some time on it last night and was able to get the latest retrieval method working, now just need to format it back how the program is expecting it.  Hopefully should have an updated version this week.

**Comment by kweitzner** [comment]
Fantastic news !

**Comment by f5snopro** [comment]
Amazing!!

**Comment by ChuckMac** [comment]
Pushed a new version out if you want to give it a try.

**Comment by kweitzner** [comment]
Just pulled new docker image and it looks good so far. Thank you so much!

**Comment by mybig731** [comment]
Hello.  First...thanks for putting all this work into this app.  I stumbled across it a week ago and am a total newbie.  I have managed to configure the GUI to my liking and am getting errors in the log saying: Request failed, Non-200 received getting reservation data: 400 when I launch the site.  The last checked is stuck on "Checking Now".  I'm wondering if I need to configure my disney account info somewhere in the code to allow for searching or if this is another issue?  Thanks in advance for any guidance.

Watching: 7532f755-ceb4-4f9e-b91e-40611e4cfb54 90001369;entityType=restaurant
Watching: b1eaf779-0e1f-4777-945a-b468da6db0dd 18733814;entityType=restaurant
Watching: 1969dd27-3449-41fc-b265-c573a7b3cfe8 90002448;entityType=restaurant
(1) wsgi starting up on http://0.0.0.0:5500
>> Request failed, Non-200 received getting reservation data: 400
>> Request failed, Non-200 received getting reservation data: 400
>> Request failed, Non-200 received getting reservation data: 400

**Comment by ChuckMac** [comment]
@mybig731 your account information is not required anywhere for the process.  I'll see if i can recreate that 400 error.

**Comment by kweitzner** [comment]
I setup two scans and forced a check and am seeing "Remote end connection
closed without response"

**Comment by f5snopro** [comment]
Same here. _"Remote end closed connection without response"_

Log says: _"Request failed, Non-200 received getting reservation data: 400"_

**Comment by ChuckMac** [comment]
I pushed a new update (0.2.1) give that one a try.

**Comment by kweitzner** [comment]
I actually am still getting it on .2.1  I ran a test to add the rest of the
ones I'm missing still and they're all failing with the same error.

**Comment by f5snopro** [comment]
I don't see the errors any more. But I have 4 restaurants selected, one of which I know has openings on the date I selected. I checked it in the mobile app. They're all sitting with Last Checked as "checking now..."

**Comment by ChuckMac** [comment]
Pushing one more update tonight... looks like the search is different depending on if its a timeframe (ex: Breakfast) vs a set time (ex: 11:00).  0.2.2 but the build process to docker takes ~45 minutes.

**Comment by kweitzner** [comment]
Appears to be working well since last update.  Seeing failures still randomly, but I assume it's some kind of throttling and not the same issue as before.

**Comment by f5snopro** [comment]
Flawless here. MANY THANKS!!

**Comment by mybig731** [comment]
Same here working wonderfully.  I really appreciate the effort!

**Comment by ChuckMac** [comment]
great I'm going to close this one out

**Comment by kweitzner** [comment]
Never mind new version fixes that. Didn't notice

Thank you for your work on this fantastic app
